# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

steps:

- task: AzurePowerShell@5
  inputs:
    azureSubscription: 'Azure-rg-chub-dev-1'
    ScriptType: 'InlineScript'
    Inline: |
      Write-Output "Install Module"
      Install-Module -Name APIManagementTemplate -Scope CurrentUser -Force
      
      Write-Output "Get token"
      $accessToken = get-azaccesstoken 
      
      Write-Output "Get API Management Template"
      
      Get-APIManagementTemplate -APIManagement apim-chub-dev-1 -ResourceGroup rg-chub-dev-1 -SubscriptionId 2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39 -TenantName networkhomes.org.uk -token $accessToken.Token  | Out-File "$(Build.SourcesDirectory)\AzureResources\ARMDeploymentTemplates\APIManagement.json"
    azurePowerShellVersion: 'LatestVersion'
- task: CmdLine@2
  inputs:
    script: |
      echo commit all changes
      git config user.email "martin.odunuga@networkhomes.org.uk"
      git config user.name "Automatic Build"
      git checkout master
      git add --all
      git commit -m "solution init"
      echo push code to new repo
      git -c http.extraheader="AUTHORIZATION: bearer $(System.AccessToken)" push origin master