# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: windows-latest

stages:
- stage: Build
  displayName: Build
  jobs:
  - job: Build
    steps:
    
    - task: NuGetToolInstaller@1
      inputs:
        versionSpec: '5.8.0'
        checkLatest: true

    - task: NuGetCommand@2
      inputs:
        command: 'restore'
        restoreSolution: 'AzureResources/AzureResources.sln'
        feedsToUse: 'select'

    - task: MSBuild@1
      displayName: "Build Data Integration Function App"
      inputs:
        solution: 'AzureResources/AzureResources.sln'
        msbuildArchitecture: 'x64'
        configuration: 'Release'
        msbuildArguments: '/p:DeployOnBuild=true /p:PublishProfile=FolderProfile /p:TransformWebConfigEnabled=false'

    - task: ArchiveFiles@2
      inputs:
        rootFolderOrFile: 'AzureResources/NH.CHUB.DataIntegration.AzureFunctions/bin/Release/net6.0'
        includeRootFolder: false
        archiveType: 'zip'
        archiveFile: '$(Build.ArtifactStagingDirectory)/DataIntegrationFunctionApp.zip'
        replaceExistingArchive: true

    - publish: "$(Build.ArtifactStagingDirectory)/DataIntegrationFunctionApp.zip"
      displayName: "Publish Data Integration Function App Files"
      artifact: DataIntegrationFunctionApp

    - task: CopyFiles@2
      displayName: 'Copy Specific Scripts'
      inputs:
        contents: '$(System.DefaultWorkingDirectory)\AzureResources\ARMDeploymentTemplates\DataIntegration*.json'
        targetFolder: '$(Build.ArtifactStagingDirectory)\AzureARMScripts'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)\AzureARMScripts'
        ArtifactName: 'AzureARMScripts'
        publishLocation: 'Container'

- stage: Dev
  displayName: "Deploy to Dev"
  jobs:
    - template: Templates/Data Integration Components Release Steps.yml
      parameters:
        environment: 'DEV'
        resourcegroup: 'dev'
        subscriptionId: '2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39'

- stage: SIT
  displayName: "Deploy to SIT"
  jobs:
    - template: Templates/Data Integration Components Release Steps.yml
      parameters:
        environment: 'SIT'
        resourcegroup: 'sit'
        subscriptionId: '2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39'

- stage: UAT
  displayName: "Deploy to UAT"
  jobs:
    - template: Templates/Data Integration Components Release Steps.yml
      parameters:
        environment: 'UAT'
        resourcegroup: 'UAT'
        subscriptionId: '2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39'

#- stage: Training
#  displayName: "Deploy to Training"
#  jobs:
#    - template: Templates/Data Integration Components Release Steps.yml
#      parameters:
#        environment: 'Training'
#        resourcegroup: 'training'
#        subscriptionId: '2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39'

- stage: SprintHotFixDev
  displayName: "Deploy to Sprint Hot Fix Dev"
  jobs:
    - template: Templates/Data Integration Components Release Steps.yml
      parameters:
        environment: 'Sprint Hot Fix Dev'
        resourcegroup: 'sprinthotfixdev'
        subscriptionId: '2e2cc2ec-9c5d-46af-9c0b-5a3b1b766e39'

- stage: PROD
  displayName: "Deploy to Prod"
  jobs:
    - template: Templates/Data Integration Components Release Steps.yml
      parameters:
        environment: 'PROD'
        resourcegroup: 'prod'
        subscriptionId: '206bebf0-39bd-4a14-a394-f426cf0f34c8'
