name: Power Apps Build and Release

on:
  workflow_dispatch:
    inputs:
      deployConfigurationData:
        description: 'Deploy Configuration Data?'
        type: boolean
        default: false
      deployAutomatedDeploymentExample:
        description: 'Deploy  Automated Example?'
        type: boolean
        default: false
      updateOrganisationSettings:
        description: 'Update Organisation Settings?'
        type: boolean
        default: false        
      deployAutomatedDeploymentExampleUATMethod:
          description: 'Deploy Automated Deployment Example UAT Method'
          default: 'Update'
          type: choice
          options:
            - Update
            - Upgrade


#variables:
 # - group: alm-accelerator-variable-group
 # - name: solutionVersion
 #   value: string
 # - name: solutionDisplayName
 #   value: string

jobs:
 Build:
  runs-on: windows-latest
  steps:  
    - uses: actions/checkout@v2
      with:
        lfs: true
        
    - name: powerplatform-actions             
      uses: microsoft/powerplatform-actions/actions-install@v1

    - name: Pack Solution
      uses: microsoft/powerplatform-actions/pack-solution@v1
      if: inputs.deployAutomatedDeploymentExample == true
      with:
         solution-folder: .\Solutions\AutomatedDeploymentExample
         solution-file: ${{ runner.temp }}\AutomatedDeploymentExample.zip
         solution-type: Both

    - name: Publish PowerShell Scripts
      uses: actions/upload-artifact@v4
      with:
        name: PipelineUtils
        path: |
          .\Deployment\PowerShell\*.ps1

    - name: Publish Solutions
      uses: actions/upload-artifact@v4
      if: inputs.deployAutomatedDeploymentExample == true
      with:
        name: Solutions
        path: |
          ${{ runner.temp }}\AutomatedDeploymentExample.zip
          ${{ runner.temp }}\AutomatedDeploymentExample_Managed.zip

    - name: Publish Solution Parameter Files
      uses: actions/upload-artifact@v4
      if: inputs.deployAutomatedDeploymentExample == true
      with:
        name: SolutionParameterFiles
        path: |
          .\Deployment\Solution Parameter Files\*.json    

    - name: Publish Flow Activation Files
      uses: actions/upload-artifact@v4
#      if: inputs.deployAutomatedDeploymentExample == true
      with:
        name: FlowActivation
        path: |
          .\Deployment\Flow Activation\*.json

    - name: Publish Data Files
      uses: actions/upload-artifact@v4
      if: inputs.deployConfigurationData == true
      with:
        name: Data
        path: |
          .\Deployment\Data\*.zip

    - name: Publish Organisation Settings Files
      uses: actions/upload-artifact@v4
      if: inputs.updateOrganisationSettings == true
      with:
        name: OrganisationSettingsFiles
        path: |
          .\Deployment\Organisation Settings Files\*.json                     

 Deploy-To-UAT:
   uses: ./.github/workflows/Power Apps Deployment Steps.yml
   needs: Build
   with:
     environment: UAT
     serviceConnectionUrl: "https://pemprodev.crm11.dynamics.com/"
     appId: "3492d4d1-7c22-4928-891b-2d8a449546cb"
     deployAutomatedDeploymentExample: ${{ inputs.deployAutomatedDeploymentExample }}
     deployAutomatedDeploymentExampleMethod: ${{ inputs.deployAutomatedDeploymentExampleUATMethod }}
     deployConfigurationData: ${{ inputs.deployConfigurationData }}
     updateOrganizationSettings: ${{ inputs.updateOrganisationSettings }}
   secrets: 
     clientSecret: ${{ secrets.DEVAPPLICATIONSECRET }}
     tenantId: ${{ secrets.TENANTID  }}
   
#- stage: UAT
#  displayName: "Deploy To UAT"
#  jobs:
#      - template: Templates/Power Apps Deployment Steps.yml
#        parameters:
#          environment: 'UAT'
#          serviceConnectionUrl: 'https://pemprodev.crm11.dynamics.com/' 
#          powerPlatformServiceConnectionName: 'Power Platform UAT'
#          deployAutomatedDeploymentExample: ${{parameters.deployAutomatedDeploymentExample}}
 #         deployAutomatedDeploymentExample2: ${{parameters.deployAutomatedDeploymentExample2}}
 #         deployConfigurationData: ${{parameters.deployConfigurationData}}
 #         updateOrganizationSettings: ${{parameters.updateOrganizationSettings}}
#          deployAutomatedDeploymentExampleMethodVariableName: 'UAT_AutomatedDeploymentExample'
#          deployAutomatedDeploymentExample2MethodVariableName: 'UAT_AutomatedDeploymentExample2'
